import './globals.css'
import connectToDatabase from '@/utils/mongodb'  // import db util

export const metadata = {
  title: 'My App',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  // Test DB connection
  connectToDatabase()
    .then(() => console.log('✅ MongoDB connection established'))
    .catch((err) => console.error('❌ MongoDB connection failed:', err));

  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
