import './globals.css';
import connectToDatabase from '@/utils/mongodb'; // DB util
import User from './models/User'; // User model

export const metadata = {
  title: 'My App',
  description: 'Generated by Next.js',
}

export default async function RootLayout({ children }) {
  // Connect to DB
  await connectToDatabase();

  // Test DB and model
  console.log('✅ MongoDB connection established');
  console.log('User model loaded successfully:', !!User);

  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
