import './globals.css';
import connectToDatabase from '@/utils/mongodb'; // DB util
import User from './models/User'; // User model
import SessionProviderWrapper from "./providers/SessionProviderWrapper"; 
import { Toaster } from 'react-hot-toast'; // ✅ added for toast

export const metadata = {
  title: 'My App',
  description: 'Generated by Next.js',
};

export default async function RootLayout({ children }) {
  // Connect to DB
  await connectToDatabase();

  // Test DB and model
  console.log('✅ MongoDB connection established');
  console.log('User model loaded successfully:', !!User);

  return (
    <html lang="en">
      <body>
        <SessionProviderWrapper>
          {children}

          {/* ✅ Toast messages visible across entire app */}
          <Toaster
            position="top-right"
            toastOptions={{
              duration: 4000,
              style: {
                background: '#363636',
                color: '#fff',
              },
              success: {
                duration: 3000,
                iconTheme: {
                  primary: '#4ade80',
                  secondary: '#fff',
                },
              },
              error: {
                duration: 4000,
                iconTheme: {
                  primary: '#ef4444',
                  secondary: '#fff',
                },
              },
            }}
          />
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
